@startuml
(*) -down---> "Fetch 'libraries' from Firestore" as startOff
if "Is Empty" then
  -up-> [true] "'Please connect to the internet'" as pleaseConnect

else
  -down->[false] "Connect with Play Developer API"
  if "isPurchased" then
  -down-> [true] "Check assets" as checkAssets
  else
  -down-> [false] "Format card:\n-Set click handler to not playable\n-Set display text to 'check it out!'"
  checkAssets if "isInstalled" as isInstalled then
  -down-> [true] "Format card:\n-Set click handler to playable\n-Set display text to 'play now'"
  -down-> (*)
endif

pleaseConnect --> startOff
@enduml